/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5MfrXsroeku
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { JSX, SVGProps } from "react"
import Image from 'next/image'
import LogoSalvador from '../assets/img/salvador.jpg'
import LogoAlma from '../assets/img/almapng.png'
import LogoMarcaAlkoat from '../assets/img/marcas/alkoat.png'
import LogoMarcaAlva from '../assets/img/marcas/arva.png'
import LogoMarcaFester from '../assets/img/marcas/fester.png'
import LogoMarcaSika from '../assets/img/marcas/sika.png'

export function ComponentAlt() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <DropletIcon className="w-8 h-8" />
          <span className="text-xl font-bold">Impermeabilizaciones Santiago</span>
        </div>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="hover:underline" prefetch={false}>
            Inicio
          </Link>
          <Link href="#servicios" className="hover:underline" prefetch={false}>
            Servicios
          </Link>
          <Link href="#proyectos" className="hover:underline" prefetch={false}>
            Proyectos
          </Link>
          <Link href="#marcas" className="hover:underline" prefetch={false}>
            Marcas
          </Link>
          <Link href="#contacto" className="hover:underline" prefetch={false}>
            Contacto
          </Link>
        </nav>
        <Button variant="outline" size="sm" className="md:hidden">
          <MenuIcon className="w-6 h-6" />
        </Button>
      </header>
      <main className="flex-1">
        <section className="hero-section py-24 px-6 text-center text-primary-foreground">
          <h1 className="text-4xl font-bold mb-4">Impermeabilizaciones Santiago</h1>
          <p className="text-lg mb-8">Expertos en soluciones de impermeabilización para tu hogar o negocio.</p>
          <Link
            href="#contacto"
            className="inline-flex items-center justify-center bg-primary px-6 py-3 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
            prefetch={false}
          >
            Solicitar Cotización
          </Link>
        </section>
        <section id="servicios" className="bg-background py-16 px-6 text-justify">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Nuestros Servicios</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-muted rounded-md p-6 shadow-md">
                <h3 className="text-2xl font-bold mb-4">Impermeabilización por Inyección</h3>
                <p className="text-muted-foreground mb-6">
                  Nuestra técnica de inyección de polímeros es la solución más efectiva para impermeabilizar grietas y
                  fisuras en muros, losas y cimientos.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                  prefetch={false}
                >
                  Más Información
                </Link>
              </div>
              <div className="bg-muted rounded-md p-6 shadow-md">
                <h3 className="text-2xl font-bold mb-4">Impermeabilización de Techos</h3>
                <p className="text-muted-foreground mb-6">
                  Ofrecemos soluciones de impermeabilización para techos planos y con pendiente, garantizando la
                  protección de tu hogar o negocio.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                  prefetch={false}
                >
                  Más Información
                </Link>
              </div>
              <div className="bg-muted rounded-md p-6 shadow-md">
                <h3 className="text-2xl font-bold mb-4">Impermeabilización de Muros</h3>
                <p className="text-muted-foreground mb-6">
                  Protegemos tus muros de la humedad y filtraciones con nuestros sistemas de impermeabilización de alta
                  calidad.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                  prefetch={false}
                >
                  Más Información
                </Link>
              </div>
              <div className="bg-muted rounded-md p-6 shadow-md">
                <h3 className="text-2xl font-bold mb-4">Impermeabilización de Cimientos</h3>
                <p className="text-muted-foreground mb-6">
                  Aseguramos la protección de tus cimientos contra la humedad y filtraciones con nuestros sistemas de
                  impermeabilización.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                  prefetch={false}
                >
                  Más Información
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section id="proyectos" className="bg-muted py-16 px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Proyectos Destacados</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-background rounded-md shadow-md">
                <Image
                  src={ LogoSalvador }
                  alt="salvador"
                  width={600}
                  height={400}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "600/400", objectFit: "contain" }}
                />
                <div className="p-6">
                  <h3 className="text-2xl font-bold mb-2">Hospital El Salvador</h3>
                  <p className="text-muted-foreground mb-4 text-justify">
                    Impermeabilización de techos y muros para un edificio corporativo en el centro de la ciudad.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                    prefetch={false}
                  >
                    Ver Más
                  </Link>
                </div>
              </div>
              <div className="bg-background rounded-md shadow-md">
                <Image
                  src={ LogoAlma}
                  alt="Proyecto 2"
                  width={600}
                  height={400}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "600/400", objectFit: "contain" }}
                />
                <div className="p-6">
                  <h3 className="text-2xl font-bold mb-2">Proyecto Alma</h3>
                  <p className="text-muted-foreground mb-4 text-justify">
                    Impermeabilización de techos y muros para un centro comercial de gran envergadura.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                    prefetch={false}
                  >
                    Ver Más
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="marcas" className="bg-background py-16 px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Marcas que Respaldan Nuestro Trabajo</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              <div className="bg-muted rounded-md p-6 flex items-center justify-center">
                <Image
                  src={ LogoMarcaAlkoat}
                  alt="Marca 1"
                  width={120}
                  height={60}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "120/60", objectFit: "contain" }}
                />
              </div>
              <div className="bg-muted rounded-md p-6 flex items-center justify-center">
                <Image
                  src={ LogoMarcaAlva }
                  alt="Marca 2"
                  width={120}
                  height={60}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "120/60", objectFit: "contain" }}
                />
              </div>
              <div className="bg-muted rounded-md p-6 flex items-center justify-center">
                <Image
                  src={ LogoMarcaFester }
                  alt="Marca 3"
                  width={120}
                  height={60}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "120/60", objectFit: "contain" }}
                />
              </div>
              <div className="bg-muted rounded-md p-6 flex items-center justify-center">
                <Image
                  src={LogoMarcaSika}
                  alt="Marca 4"
                  width={120}
                  height={60}
                  className="rounded-t-md object-cover w-full h-56"
                  style={{ aspectRatio: "120/60", objectFit: "contain" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section id="contacto" className="bg-muted py-16 px-6">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Contacta con Nosotros</h2>
            <form className="bg-background rounded-md shadow-md p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <Label htmlFor="nombre">Nombre</Label>
                  <Input id="nombre" type="text" placeholder="Ingresa tu nombre" />
                </div>
                <div>
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" type="email" placeholder="Ingresa tu email" />
                </div>
                <div>
                  <Label htmlFor="telefono">Teléfono</Label>
                  <Input id="telefono" type="tel" placeholder="Ingresa tu teléfono" />
                </div>
                <div>
                  <Label htmlFor="servicio">Servicio Solicitado</Label>
                  <Select>
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="Selecciona un servicio" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="inyeccion">Impermeabilización por Inyección</SelectItem>
                      <SelectItem value="techos">Impermeabilización de Techos</SelectItem>
                      <SelectItem value="muros">Impermeabilización de Muros</SelectItem>
                      <SelectItem value="cimientos">Impermeabilización de Cimientos</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div>
                <Label htmlFor="mensaje">Mensaje</Label>
                <Textarea id="mensaje" placeholder="Escribe tu mensaje" />
              </div>
              <Button type="submit" className="w-full mt-6">
                Enviar Cotización
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <DropletIcon className="w-6 h-6" />
          <span>Impermeabilizaciones Santiago</span>
        </div>
        <div className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Política de Privacidad
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Términos y Condiciones
          </Link>
          <div className="flex items-center gap-2">
            <Link href="#" className="hover:underline" prefetch={false}>
              <InstagramIcon className="w-6 h-6" />
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              <TwitterIcon className="w-6 h-6" />
            </Link>
            <Link href="https://www.tiktok.com/?lang=es" className="hover:underline" prefetch={false}>
              <TikTokIcon className="w-6 h-6" />
            </Link>

          </div>
        </div>
      </footer>
    </div>
  )
}

function DropletIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}

function TikTokIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
  <svg 
  {...props}
  xmlns="http://www.w3.org/2000/svg" 
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  strokeWidth="2"
  strokeLinecap="round"
  strokeLinejoin="round"
  >
  <path d="M448 209.9a210.1 210.1 0 0 1 -122.8-39.3V349.4A162.6 162.6 0 1 1 185 188.3V278.2a74.6 74.6 0 1 0 52.2 71.2V0l88 0a121.2 121.2 0 0 0 1.9 22.2h0A122.2 122.2 0 0 0 381 102.4a121.4 121.4 0 0 0 67 20.1z"/>
  </svg>
  )
}
export default ComponentAlt